### PR TITLE
Fix issue #39

### PR DESCRIPTION
**Pull request by razinc**
Please feedback if any requirements are not fulfilled. Thanks.

### CODE REVIEW

**Comment by caternuson** [comment]
As another idea - how about just having a single file `ads1x15_simpletest.py` that has the code for both ADS1015 and ADS1115 with the lines for one of them commented out? And a code comment that says something like `# uncomment the lines for the version you have`.

Could the import be done in a more agnostic way to help reduce the number of lines?

**Comment by razinc** [comment]
Hi @tannewt. May I know which script will used it? So, I can understand why I only need to rename 1 file.

**Comment by tannewt** [comment]
@razinc The script that validates properties of our libraries is here: https://github.com/adafruit/adabot/blob/master/adabot/lib/circuitpython_library_validators.py#L558

**Comment by razinc** [comment]
Change required is done.

**Comment by caternuson** [comment]
You'll need to update the `examples.rst` file as well:
image
Simple edit - just need to change filename to match.

**Pull request merged**
