### PR TITLE
Fast channel reads via context manager

### PR DESCRIPTION
**Pull request by caternuson**
Not perfect, but helps. Proposed fix for #27.

### CODE REVIEW

**Comment by ladyada** [comment]
question - could we 'cache' the config register value, and if the pin has changed, send and if pin has not changed, skip that? then you dont have to have a separate 'fast' flag

**Comment by caternuson** [comment]
Maybe. I was thinking the current way it works would be preserved. It's not efficient, but works. And if someone just loops on a single channel, nothing special happens. This would be single-shot / "slow". Nice and simple. How it currently works and hopefully should work for most cases.
```python
for i in range(samples):
    data[i] = chan0.value
```
There are caveats to the fast read, so wanted to make it more explicit that it's being used, i.e. the context manager. This would be continuous / "fast". For more advanced uses.
```python
with chan0 as chan:
    for i in range(samples):
        data[i] = chan.value
```
So you actually have to turn it on. It doesn't just kick in automagically.

Hmm. Could maybe move the `fast` parameter to a member variable of `ADS1x15` and then turn it on/off with `@property` style access? Same general idea as what's currently in place, just changing the way it's triggered.

**Comment by caternuson** [comment]
...but easy enough to try out. @ladyada checkout PR #33 which takes the caching approach.

**Comment by caternuson** [comment]
Closing this. Going with the approach taken in PR #33 .

**Pull request closed without merging**
